#!/bin/env bash

TARGET_DIR="${1:-.}"

find "$TARGET_DIR" -type f \( -name "*.c" -o -name "*.h" \) | while read -r FILE; do
    TMP_FILE=$(mktemp)

    # convert 4 spaces to tabs
    # strip trailing whitespace
    # Convert CRLF to LF (dos2unix logic)
    # ensure file ends with a single newline
    sed 's/    /\t/g; s/[[:space:]]*$//; s/\r$//' "$FILE" > "$TMP_FILE"
    sed -i -e '${/^$/!q;}' -e '${G;}' "$TMP_FILE"

    if ! cmp -s "$FILE" "$TMP_FILE"; then
        mv "$TMP_FILE" "$FILE"
        echo "updated: $FILE"
    else
        rm -f "$TMP_FILE"
    fi
done