#!/bin/env bash

DISK_IMG="disk.img"
ISO_IMG="build/Cuore.x86-64.iso"
QEMU_FIRMWARE="/usr/share/OVMF/OVMF_CODE.fd"

if [ ! -f "$DISK_IMG" ]; then
    qemu-img create -f raw "$DISK_IMG" 64M
fi

qemu-system-x86_64 \
    -machine pc \
    -bios $QEMU_FIRMWARE \
    -drive file="$DISK_IMG",format=raw,index=0,media=disk \
    -cdrom "$ISO_IMG" \
    -m 256M \
    -serial stdio \
    -device rtl8139,netdev=u1 \
    -netdev user,id=u1
