#pragma once

void irq_handler_32(void);
void irq_handler_33(void);
void irq_handler_34(void);
void irq_handler_35(void);
void irq_handler_36(void);
void irq_handler_37(void);
void irq_handler_38(void);
void irq_handler_39(void);
void irq_handler_40(void);
void irq_handler_41(void);
void irq_handler_42(void);
void irq_handler_43(void);
void irq_handler_44(void);
void irq_handler_45(void);
void irq_handler_46(void);
void irq_handler_47(void);
void irq_handler_48(void);
void irq_handler_49(void);
void irq_handler_50(void);
void irq_handler_51(void);
void irq_handler_52(void);
void irq_handler_53(void);
void irq_handler_54(void);
void irq_handler_55(void);
void irq_handler_56(void);
void irq_handler_57(void);
void irq_handler_58(void);
void irq_handler_59(void);
void irq_handler_60(void);
void irq_handler_61(void);
void irq_handler_62(void);
void irq_handler_63(void);
void irq_handler_64(void);
void irq_handler_65(void);
void irq_handler_66(void);
void irq_handler_67(void);
void irq_handler_68(void);
void irq_handler_69(void);
void irq_handler_70(void);
void irq_handler_71(void);
void irq_handler_72(void);
void irq_handler_73(void);
void irq_handler_74(void);
void irq_handler_75(void);
void irq_handler_76(void);
void irq_handler_77(void);
void irq_handler_78(void);
void irq_handler_79(void);
void irq_handler_80(void);
void irq_handler_81(void);
void irq_handler_82(void);
void irq_handler_83(void);
void irq_handler_84(void);
void irq_handler_85(void);
void irq_handler_86(void);
void irq_handler_87(void);
void irq_handler_88(void);
void irq_handler_89(void);
void irq_handler_90(void);
void irq_handler_91(void);
void irq_handler_92(void);
void irq_handler_93(void);
void irq_handler_94(void);
void irq_handler_95(void);
void irq_handler_96(void);
void irq_handler_97(void);
void irq_handler_98(void);
void irq_handler_99(void);
void irq_handler_100(void);
void irq_handler_101(void);
void irq_handler_102(void);
void irq_handler_103(void);
void irq_handler_104(void);
void irq_handler_105(void);
void irq_handler_106(void);
void irq_handler_107(void);
void irq_handler_108(void);
void irq_handler_109(void);
void irq_handler_110(void);
void irq_handler_111(void);
void irq_handler_112(void);
void irq_handler_113(void);
void irq_handler_114(void);
void irq_handler_115(void);
void irq_handler_116(void);
void irq_handler_117(void);
void irq_handler_118(void);
void irq_handler_119(void);
void irq_handler_120(void);
void irq_handler_121(void);
void irq_handler_122(void);
void irq_handler_123(void);
void irq_handler_124(void);
void irq_handler_125(void);
void irq_handler_126(void);
void irq_handler_127(void);
void irq_handler_128(void);
void irq_handler_129(void);
void irq_handler_130(void);
void irq_handler_131(void);
void irq_handler_132(void);
void irq_handler_133(void);
void irq_handler_134(void);
void irq_handler_135(void);
void irq_handler_136(void);
void irq_handler_137(void);
void irq_handler_138(void);
void irq_handler_139(void);
void irq_handler_140(void);
void irq_handler_141(void);
void irq_handler_142(void);
void irq_handler_143(void);
void irq_handler_144(void);
void irq_handler_145(void);
void irq_handler_146(void);
void irq_handler_147(void);
void irq_handler_148(void);
void irq_handler_149(void);
void irq_handler_150(void);
void irq_handler_151(void);
void irq_handler_152(void);
void irq_handler_153(void);
void irq_handler_154(void);
void irq_handler_155(void);
void irq_handler_156(void);
void irq_handler_157(void);
void irq_handler_158(void);
void irq_handler_159(void);
void irq_handler_160(void);
void irq_handler_161(void);
void irq_handler_162(void);
void irq_handler_163(void);
void irq_handler_164(void);
void irq_handler_165(void);
void irq_handler_166(void);
void irq_handler_167(void);
void irq_handler_168(void);
void irq_handler_169(void);
void irq_handler_170(void);
void irq_handler_171(void);
void irq_handler_172(void);
void irq_handler_173(void);
void irq_handler_174(void);
void irq_handler_175(void);
void irq_handler_176(void);
void irq_handler_177(void);
void irq_handler_178(void);
void irq_handler_179(void);
void irq_handler_180(void);
void irq_handler_181(void);
void irq_handler_182(void);
void irq_handler_183(void);
void irq_handler_184(void);
void irq_handler_185(void);
void irq_handler_186(void);
void irq_handler_187(void);
void irq_handler_188(void);
void irq_handler_189(void);
void irq_handler_190(void);
void irq_handler_191(void);
void irq_handler_192(void);
void irq_handler_193(void);
void irq_handler_194(void);
void irq_handler_195(void);
void irq_handler_196(void);
void irq_handler_197(void);
void irq_handler_198(void);
void irq_handler_199(void);
void irq_handler_200(void);
void irq_handler_201(void);
void irq_handler_202(void);
void irq_handler_203(void);
void irq_handler_204(void);
void irq_handler_205(void);
void irq_handler_206(void);
void irq_handler_207(void);
void irq_handler_208(void);
void irq_handler_209(void);
void irq_handler_210(void);
void irq_handler_211(void);
void irq_handler_212(void);
void irq_handler_213(void);
void irq_handler_214(void);
void irq_handler_215(void);
void irq_handler_216(void);
void irq_handler_217(void);
void irq_handler_218(void);
void irq_handler_219(void);
void irq_handler_220(void);
void irq_handler_221(void);
void irq_handler_222(void);
void irq_handler_223(void);
void irq_handler_224(void);
void irq_handler_225(void);
void irq_handler_226(void);
void irq_handler_227(void);
void irq_handler_228(void);
void irq_handler_229(void);
void irq_handler_230(void);
void irq_handler_231(void);
void irq_handler_232(void);
void irq_handler_233(void);
void irq_handler_234(void);
void irq_handler_235(void);
void irq_handler_236(void);
void irq_handler_237(void);
void irq_handler_238(void);
void irq_handler_239(void);
void irq_handler_240(void);
void irq_handler_241(void);
void irq_handler_242(void);
void irq_handler_243(void);
void irq_handler_244(void);
void irq_handler_245(void);
void irq_handler_246(void);
void irq_handler_247(void);
void irq_handler_248(void);
void irq_handler_249(void);
void irq_handler_250(void);
void irq_handler_251(void);
void irq_handler_252(void);
void irq_handler_253(void);
void irq_handler_254(void);
void irq_handler_255(void);

DEF_IRQ_HANDLER(32, irq_dispatch)
DEF_IRQ_HANDLER(33, irq_dispatch)
DEF_IRQ_HANDLER(34, irq_dispatch)
DEF_IRQ_HANDLER(35, irq_dispatch)
DEF_IRQ_HANDLER(36, irq_dispatch)
DEF_IRQ_HANDLER(37, irq_dispatch)
DEF_IRQ_HANDLER(38, irq_dispatch)
DEF_IRQ_HANDLER(39, irq_dispatch)
DEF_IRQ_HANDLER(40, irq_dispatch)
DEF_IRQ_HANDLER(41, irq_dispatch)
DEF_IRQ_HANDLER(42, irq_dispatch)
DEF_IRQ_HANDLER(43, irq_dispatch)
DEF_IRQ_HANDLER(44, irq_dispatch)
DEF_IRQ_HANDLER(45, irq_dispatch)
DEF_IRQ_HANDLER(46, irq_dispatch)
DEF_IRQ_HANDLER(47, irq_dispatch)
DEF_IRQ_HANDLER(48, irq_dispatch)
DEF_IRQ_HANDLER(49, irq_dispatch)
DEF_IRQ_HANDLER(50, irq_dispatch)
DEF_IRQ_HANDLER(51, irq_dispatch)
DEF_IRQ_HANDLER(52, irq_dispatch)
DEF_IRQ_HANDLER(53, irq_dispatch)
DEF_IRQ_HANDLER(54, irq_dispatch)
DEF_IRQ_HANDLER(55, irq_dispatch)
DEF_IRQ_HANDLER(56, irq_dispatch)
DEF_IRQ_HANDLER(57, irq_dispatch)
DEF_IRQ_HANDLER(58, irq_dispatch)
DEF_IRQ_HANDLER(59, irq_dispatch)
DEF_IRQ_HANDLER(60, irq_dispatch)
DEF_IRQ_HANDLER(61, irq_dispatch)
DEF_IRQ_HANDLER(62, irq_dispatch)
DEF_IRQ_HANDLER(63, irq_dispatch)
DEF_IRQ_HANDLER(64, irq_dispatch)
DEF_IRQ_HANDLER(65, irq_dispatch)
DEF_IRQ_HANDLER(66, irq_dispatch)
DEF_IRQ_HANDLER(67, irq_dispatch)
DEF_IRQ_HANDLER(68, irq_dispatch)
DEF_IRQ_HANDLER(69, irq_dispatch)
DEF_IRQ_HANDLER(70, irq_dispatch)
DEF_IRQ_HANDLER(71, irq_dispatch)
DEF_IRQ_HANDLER(72, irq_dispatch)
DEF_IRQ_HANDLER(73, irq_dispatch)
DEF_IRQ_HANDLER(74, irq_dispatch)
DEF_IRQ_HANDLER(75, irq_dispatch)
DEF_IRQ_HANDLER(76, irq_dispatch)
DEF_IRQ_HANDLER(77, irq_dispatch)
DEF_IRQ_HANDLER(78, irq_dispatch)
DEF_IRQ_HANDLER(79, irq_dispatch)
DEF_IRQ_HANDLER(80, irq_dispatch)
DEF_IRQ_HANDLER(81, irq_dispatch)
DEF_IRQ_HANDLER(82, irq_dispatch)
DEF_IRQ_HANDLER(83, irq_dispatch)
DEF_IRQ_HANDLER(84, irq_dispatch)
DEF_IRQ_HANDLER(85, irq_dispatch)
DEF_IRQ_HANDLER(86, irq_dispatch)
DEF_IRQ_HANDLER(87, irq_dispatch)
DEF_IRQ_HANDLER(88, irq_dispatch)
DEF_IRQ_HANDLER(89, irq_dispatch)
DEF_IRQ_HANDLER(90, irq_dispatch)
DEF_IRQ_HANDLER(91, irq_dispatch)
DEF_IRQ_HANDLER(92, irq_dispatch)
DEF_IRQ_HANDLER(93, irq_dispatch)
DEF_IRQ_HANDLER(94, irq_dispatch)
DEF_IRQ_HANDLER(95, irq_dispatch)
DEF_IRQ_HANDLER(96, irq_dispatch)
DEF_IRQ_HANDLER(97, irq_dispatch)
DEF_IRQ_HANDLER(98, irq_dispatch)
DEF_IRQ_HANDLER(99, irq_dispatch)
DEF_IRQ_HANDLER(100, irq_dispatch)
DEF_IRQ_HANDLER(101, irq_dispatch)
DEF_IRQ_HANDLER(102, irq_dispatch)
DEF_IRQ_HANDLER(103, irq_dispatch)
DEF_IRQ_HANDLER(104, irq_dispatch)
DEF_IRQ_HANDLER(105, irq_dispatch)
DEF_IRQ_HANDLER(106, irq_dispatch)
DEF_IRQ_HANDLER(107, irq_dispatch)
DEF_IRQ_HANDLER(108, irq_dispatch)
DEF_IRQ_HANDLER(109, irq_dispatch)
DEF_IRQ_HANDLER(110, irq_dispatch)
DEF_IRQ_HANDLER(111, irq_dispatch)
DEF_IRQ_HANDLER(112, irq_dispatch)
DEF_IRQ_HANDLER(113, irq_dispatch)
DEF_IRQ_HANDLER(114, irq_dispatch)
DEF_IRQ_HANDLER(115, irq_dispatch)
DEF_IRQ_HANDLER(116, irq_dispatch)
DEF_IRQ_HANDLER(117, irq_dispatch)
DEF_IRQ_HANDLER(118, irq_dispatch)
DEF_IRQ_HANDLER(119, irq_dispatch)
DEF_IRQ_HANDLER(120, irq_dispatch)
DEF_IRQ_HANDLER(121, irq_dispatch)
DEF_IRQ_HANDLER(122, irq_dispatch)
DEF_IRQ_HANDLER(123, irq_dispatch)
DEF_IRQ_HANDLER(124, irq_dispatch)
DEF_IRQ_HANDLER(125, irq_dispatch)
DEF_IRQ_HANDLER(126, irq_dispatch)
DEF_IRQ_HANDLER(127, irq_dispatch)
DEF_IRQ_HANDLER(128, irq_dispatch)
DEF_IRQ_HANDLER(129, irq_dispatch)
DEF_IRQ_HANDLER(130, irq_dispatch)
DEF_IRQ_HANDLER(131, irq_dispatch)
DEF_IRQ_HANDLER(132, irq_dispatch)
DEF_IRQ_HANDLER(133, irq_dispatch)
DEF_IRQ_HANDLER(134, irq_dispatch)
DEF_IRQ_HANDLER(135, irq_dispatch)
DEF_IRQ_HANDLER(136, irq_dispatch)
DEF_IRQ_HANDLER(137, irq_dispatch)
DEF_IRQ_HANDLER(138, irq_dispatch)
DEF_IRQ_HANDLER(139, irq_dispatch)
DEF_IRQ_HANDLER(140, irq_dispatch)
DEF_IRQ_HANDLER(141, irq_dispatch)
DEF_IRQ_HANDLER(142, irq_dispatch)
DEF_IRQ_HANDLER(143, irq_dispatch)
DEF_IRQ_HANDLER(144, irq_dispatch)
DEF_IRQ_HANDLER(145, irq_dispatch)
DEF_IRQ_HANDLER(146, irq_dispatch)
DEF_IRQ_HANDLER(147, irq_dispatch)
DEF_IRQ_HANDLER(148, irq_dispatch)
DEF_IRQ_HANDLER(149, irq_dispatch)
DEF_IRQ_HANDLER(150, irq_dispatch)
DEF_IRQ_HANDLER(151, irq_dispatch)
DEF_IRQ_HANDLER(152, irq_dispatch)
DEF_IRQ_HANDLER(153, irq_dispatch)
DEF_IRQ_HANDLER(154, irq_dispatch)
DEF_IRQ_HANDLER(155, irq_dispatch)
DEF_IRQ_HANDLER(156, irq_dispatch)
DEF_IRQ_HANDLER(157, irq_dispatch)
DEF_IRQ_HANDLER(158, irq_dispatch)
DEF_IRQ_HANDLER(159, irq_dispatch)
DEF_IRQ_HANDLER(160, irq_dispatch)
DEF_IRQ_HANDLER(161, irq_dispatch)
DEF_IRQ_HANDLER(162, irq_dispatch)
DEF_IRQ_HANDLER(163, irq_dispatch)
DEF_IRQ_HANDLER(164, irq_dispatch)
DEF_IRQ_HANDLER(165, irq_dispatch)
DEF_IRQ_HANDLER(166, irq_dispatch)
DEF_IRQ_HANDLER(167, irq_dispatch)
DEF_IRQ_HANDLER(168, irq_dispatch)
DEF_IRQ_HANDLER(169, irq_dispatch)
DEF_IRQ_HANDLER(170, irq_dispatch)
DEF_IRQ_HANDLER(171, irq_dispatch)
DEF_IRQ_HANDLER(172, irq_dispatch)
DEF_IRQ_HANDLER(173, irq_dispatch)
DEF_IRQ_HANDLER(174, irq_dispatch)
DEF_IRQ_HANDLER(175, irq_dispatch)
DEF_IRQ_HANDLER(176, irq_dispatch)
DEF_IRQ_HANDLER(177, irq_dispatch)
DEF_IRQ_HANDLER(178, irq_dispatch)
DEF_IRQ_HANDLER(179, irq_dispatch)
DEF_IRQ_HANDLER(180, irq_dispatch)
DEF_IRQ_HANDLER(181, irq_dispatch)
DEF_IRQ_HANDLER(182, irq_dispatch)
DEF_IRQ_HANDLER(183, irq_dispatch)
DEF_IRQ_HANDLER(184, irq_dispatch)
DEF_IRQ_HANDLER(185, irq_dispatch)
DEF_IRQ_HANDLER(186, irq_dispatch)
DEF_IRQ_HANDLER(187, irq_dispatch)
DEF_IRQ_HANDLER(188, irq_dispatch)
DEF_IRQ_HANDLER(189, irq_dispatch)
DEF_IRQ_HANDLER(190, irq_dispatch)
DEF_IRQ_HANDLER(191, irq_dispatch)
DEF_IRQ_HANDLER(192, irq_dispatch)
DEF_IRQ_HANDLER(193, irq_dispatch)
DEF_IRQ_HANDLER(194, irq_dispatch)
DEF_IRQ_HANDLER(195, irq_dispatch)
DEF_IRQ_HANDLER(196, irq_dispatch)
DEF_IRQ_HANDLER(197, irq_dispatch)
DEF_IRQ_HANDLER(198, irq_dispatch)
DEF_IRQ_HANDLER(199, irq_dispatch)
DEF_IRQ_HANDLER(200, irq_dispatch)
DEF_IRQ_HANDLER(201, irq_dispatch)
DEF_IRQ_HANDLER(202, irq_dispatch)
DEF_IRQ_HANDLER(203, irq_dispatch)
DEF_IRQ_HANDLER(204, irq_dispatch)
DEF_IRQ_HANDLER(205, irq_dispatch)
DEF_IRQ_HANDLER(206, irq_dispatch)
DEF_IRQ_HANDLER(207, irq_dispatch)
DEF_IRQ_HANDLER(208, irq_dispatch)
DEF_IRQ_HANDLER(209, irq_dispatch)
DEF_IRQ_HANDLER(210, irq_dispatch)
DEF_IRQ_HANDLER(211, irq_dispatch)
DEF_IRQ_HANDLER(212, irq_dispatch)
DEF_IRQ_HANDLER(213, irq_dispatch)
DEF_IRQ_HANDLER(214, irq_dispatch)
DEF_IRQ_HANDLER(215, irq_dispatch)
DEF_IRQ_HANDLER(216, irq_dispatch)
DEF_IRQ_HANDLER(217, irq_dispatch)
DEF_IRQ_HANDLER(218, irq_dispatch)
DEF_IRQ_HANDLER(219, irq_dispatch)
DEF_IRQ_HANDLER(220, irq_dispatch)
DEF_IRQ_HANDLER(221, irq_dispatch)
DEF_IRQ_HANDLER(222, irq_dispatch)
DEF_IRQ_HANDLER(223, irq_dispatch)
DEF_IRQ_HANDLER(224, irq_dispatch)
DEF_IRQ_HANDLER(225, irq_dispatch)
DEF_IRQ_HANDLER(226, irq_dispatch)
DEF_IRQ_HANDLER(227, irq_dispatch)
DEF_IRQ_HANDLER(228, irq_dispatch)
DEF_IRQ_HANDLER(229, irq_dispatch)
DEF_IRQ_HANDLER(230, irq_dispatch)
DEF_IRQ_HANDLER(231, irq_dispatch)
DEF_IRQ_HANDLER(232, irq_dispatch)
DEF_IRQ_HANDLER(233, irq_dispatch)
DEF_IRQ_HANDLER(234, irq_dispatch)
DEF_IRQ_HANDLER(235, irq_dispatch)
DEF_IRQ_HANDLER(236, irq_dispatch)
DEF_IRQ_HANDLER(237, irq_dispatch)
DEF_IRQ_HANDLER(238, irq_dispatch)
DEF_IRQ_HANDLER(239, irq_dispatch)
DEF_IRQ_HANDLER(240, irq_dispatch)
DEF_IRQ_HANDLER(241, irq_dispatch)
DEF_IRQ_HANDLER(242, irq_dispatch)
DEF_IRQ_HANDLER(243, irq_dispatch)
DEF_IRQ_HANDLER(244, irq_dispatch)
DEF_IRQ_HANDLER(245, irq_dispatch)
DEF_IRQ_HANDLER(246, irq_dispatch)
DEF_IRQ_HANDLER(247, irq_dispatch)
DEF_IRQ_HANDLER(248, irq_dispatch)
DEF_IRQ_HANDLER(249, irq_dispatch)
DEF_IRQ_HANDLER(250, irq_dispatch)
DEF_IRQ_HANDLER(251, irq_dispatch)
DEF_IRQ_HANDLER(252, irq_dispatch)
DEF_IRQ_HANDLER(253, irq_dispatch)
DEF_IRQ_HANDLER(254, irq_dispatch)
