import os, sys
import curses

if len(sys.argv) == 2:
    CUOREOS_VERSION_NAME = sys.argv[1]
else:
    CUOREOS_VERSION_NAME = ""

os.environ.setdefault('ESCDELAY', '25')

# defaults but also acts as the template for the menu layout
# anything starting with "md" is just bookkeeping for configscreen
config_groups = {
    "compiling": {
        "mdname": "Compiling",
        "profile": "debug",
        "cc": "gcc",
        "additional_cflags": "",
        "additional_ldflags": ""
    },
    "booting": {
        "mdname": "Booting",
        "uefi_support": "true",
        "bios_support": "true",
    },
    "modules": {
        "mdname": "Modules",
        "ide_support": "true"
    },
    "devices": {
        "mdname": "Devices",
        "max_char_devices": "9",
        "max_disk_devices": "9"
    },
    "multicore": {
        "mdname": "Symmetric Multiprocessing",
        "max_cores": "255"
    },
    "sources": {
        "mdname": "Download Sources",
        "limine": "https://github.com/Limine-Bootloader/Limine.git",
        "limine_flags": "--depth=1 --branch v10.x-binary",
        "flanterm": "https://github.com/Mintsuki/Flanterm.git",
        "flanterm_flags": "--depth=1"
    }
}

def load_existing_config():
    if not os.path.exists("Config.mk"):
        return
    try:
        with open("Config.mk", "r") as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith("#") or ":=" not in line:
                    continue

                key_part, val_part = line.split(":=", 1)

                clean_key = key_part.replace("CONFIG_", "").strip().lower()
                clean_val = val_part.strip()

                for group_key in config_groups:
                    if clean_key in config_groups[group_key]:
                        config_groups[group_key][clean_key] = clean_val
    except Exception as e:
        pass

def save_config():
    try:
        with open("Config.mk", "w") as f:
            f.write("# This file is automatically generated by tools/configscreen.py.\n# This file can be modified directly with no consequences. configscreen will see your changes.\n\n")

            for group_name, settings in config_groups.items():
                f.write(f"# SECTION: {settings['mdname']}\n")
                for key, val in settings.items():
                    if key == "mdname":
                        continue
                    f.write(f"CONFIG_{key.upper()} := {val}\n")
                f.write("\n")
    except Exception as e:
        pass

def get_input(stdscr, prompt, existing):
    curses.noecho()
    curses.curs_set(1)
    h, w = stdscr.getmaxyx()

    prompt_text = f" {prompt}: "
    input_str = str(existing)
    cursor_pos = len(input_str)

    while True:
        stdscr.move(h - 2, 0)
        stdscr.clrtoeol()
        stdscr.addstr(h - 2, 2, prompt_text, curses.A_BOLD)

        start_x = 2 + len(prompt_text)
        stdscr.addstr(h - 2, start_x, input_str)

        stdscr.move(h - 2, start_x + cursor_pos)
        stdscr.refresh()

        ch = stdscr.getch()

        if ch == 27: # ESC
            curses.curs_set(0)
            return existing

        elif ch in [10, 13]: # ENTER
            curses.curs_set(0)
            return input_str

        elif ch == curses.KEY_LEFT:
            if cursor_pos > 0:
                cursor_pos -= 1

        elif ch == curses.KEY_RIGHT:
            if cursor_pos < len(input_str):
                cursor_pos += 1

        elif ch in [curses.KEY_BACKSPACE, 127, 8]:
            if cursor_pos > 0:
                input_str = input_str[:cursor_pos-1] + input_str[cursor_pos:]
                cursor_pos -= 1

        elif ch == curses.KEY_DC: # Delete key
            if cursor_pos < len(input_str):
                input_str = input_str[:cursor_pos] + input_str[cursor_pos+1:]

        elif 32 <= ch <= 126:
            if len(prompt_text) + len(input_str) < w - 5:
                input_str = input_str[:cursor_pos] + chr(ch) + input_str[cursor_pos:]
                cursor_pos += 1

def draw_window(stdscr, title, items, selected_index):
    stdscr.erase()
    h, w = stdscr.getmaxyx()

    stdscr.attron(curses.color_pair(2))
    status_bar = f" CuoreOS [{CUOREOS_VERSION_NAME}] / configscreen / [c] Clear value / [s] Save and exit / [ESC] Back / [q] Quit"
    stdscr.addstr(0, 0, status_bar + " " * (w - len(status_bar) - 1))
    stdscr.attroff(curses.color_pair(2))

    stdscr.addstr(2, 4, f" {title} ", curses.A_REVERSE)
    stdscr.addstr(3, 4, " " + "-" * (len(title) + 2))

    for i, (display_name, key) in enumerate(items):
        y = 5 + i
        x = 4
        if i == selected_index:
            stdscr.attron(curses.color_pair(1))
            stdscr.addstr(y, x, f" > {display_name} ")
            stdscr.attroff(curses.color_pair(1))
        else:
            stdscr.attron(curses.color_pair(2))
            stdscr.addstr(y, x, f"   {display_name} ")
            stdscr.attroff(curses.color_pair(2))

    stdscr.refresh()

def main(stdscr):
    curses.start_color()

    curses.init_pair(1, curses.COLOR_BLACK, curses.COLOR_CYAN)
    curses.init_pair(2, curses.COLOR_WHITE, curses.COLOR_BLUE)
    stdscr.bkgd(' ', curses.color_pair(2))

    curses.curs_set(0)
    load_existing_config()

    in_submenu = False
    active_group_key = None
    main_menu_idx = 0
    sub_menu_idx = 0

    while True:
        if not in_submenu:
            title = "Main Menu"
            keys = list(config_groups.keys())
            items = [(config_groups[k]["mdname"], k) for k in keys]
            current_idx = main_menu_idx
        else:
            group = config_groups[active_group_key]
            title = group["mdname"]
            items = [(f"{k:15}: {v}", k) for k, v in group.items() if k != "mdname"]
            current_idx = sub_menu_idx

        draw_window(stdscr, title, items, current_idx)

        key = stdscr.getch()

        if key in [ord('s'), ord('S')]:
            save_config()
            break

        elif key == 27: # ESC
            if in_submenu:
                in_submenu = False
                current_idx = 0
            else:
                break

        elif key == curses.KEY_LEFT:
            if in_submenu:
                in_submenu = False
                current_idx = 0

        elif key in [ord('q'), ord('Q')]:
            break

        elif key == curses.KEY_UP:
            current_idx = max(0, current_idx - 1)

        elif key == curses.KEY_DOWN:
            current_idx = min(len(items) - 1, current_idx + 1)

        elif key in [curses.KEY_ENTER, 10, 13, curses.KEY_RIGHT]:
            if not in_submenu:
                active_group_key = items[current_idx][1]
                in_submenu = True
                current_idx = 0
            else:
                target_key = items[current_idx][1]
                current_val = config_groups[active_group_key][target_key]
                new_val = get_input(stdscr, f"Edit {target_key}", current_val)
                config_groups[active_group_key][target_key] = new_val

        elif key in [ord('c'), ord('C')]:
            if in_submenu:
                target_key = items[current_idx][1]
                config_groups[active_group_key][target_key] = ""

        if in_submenu:
            sub_menu_idx = current_idx
        else:
            main_menu_idx = current_idx

if __name__ == "__main__":
    try:
        curses.wrapper(main)
    except KeyboardInterrupt:
        pass
